### ISSUE TITLE
MarkDown linter always failing with two pages

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/git-queue#135]
Sometimes MegaLinter fails with the Markdown linter because it can't find some URL. Normally the error disappears if you try again. I suppose it's because the inter has a timeout to load the URL.

In this case, the error hasn't disappeared even after trying more than two times:

```
  ERROR: 2 dead links found!
  [✖] https://docs.github.com/en/actions/using-jobs/using-concurrency → Status: 403
  [✖] https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments-and-hardware-resources → Status: 403
```

And it's not a "not found" error.

We have to find out why it's returning a 403 error here and also if maybe we can increase the timeout. The problem could also be that the requests are too fast. We could remove this check but I think it's a good one because we are sure there is no broken link so we keep our docs synced with GitHub's docs.

**Comment by josecelano** [comment]
I can reproduce the error locally with:

```
mega-linter-runner -e 'ENABLE=MARKDOWN'
```

and 

```s
wget https://docs.github.com/en/actions/using-jobs/using-concurrency
--2022-04-13 13:30:42--  https://docs.github.com/en/actions/using-jobs/using-concurrency
Resolving docs.github.com (docs.github.com)... 185.199.110.154, 185.199.108.154, 185.199.109.154, ...
Connecting to docs.github.com (docs.github.com)|185.199.110.154|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-04-13 13:30:43 ERROR 403: Forbidden.
```

**Comment by josecelano** [comment]
Other people are having the [same issue](https://github.com/github/feedback/discussions/14773) and it seems it only happens with subdomains: `docs.github.com`, `help.github.com`.

**Comment by josecelano** [comment]
One of the markdown errors is not related to GitHub subdomain links:

```
### Processed [MARKDOWN] files
- Using [markdownlint v0.31.1] https://megalinter.github.io/v5/descriptors/markdown_markdownlint
- MegaLinter key: [MARKDOWN_MARKDOWNLINT]
- Rules config: [.markdownlint.json]
[markdownlint] README.md - FIXED
[markdownlint] src/__tests__/README.md - FIXED
--Error detail:
/tmp/lint/README.md:3:401 MD013/line-length Line length [Expected: 400; Actual: 768]
```

It's only because the line with workflow status badges is too long. I'm going to fix it within this issue.

**Comment by da2ce7** [comment]
Reopen, Issue with merge loosing gpg signatures.

**Comment by josecelano** [comment]
I think the gpg signatures were lost because I sued the "rebase and merge" GitHub button. Read [more](https://github.com/Nautilus-Cyberneering/git-queue/pull/141#issuecomment-1101379609).

**Comment by josecelano** [comment]
@ivanramosnet has found out that you can fix this issue by adding a config file:

`.markdown-link-check.json`

```json
{
  "httpHeaders": [
    {
      "urls": ["https://docs.github.com/"],
      "headers": {
        "Accept-Encoding": "zstd, br, gzip, deflate"
      }
    }
  ]
}
```

See [this commit](https://github.com/Nautilus-Cyberneering/GPG-Bootcamp/pull/7/commits/9e92348ba69cdb0242babda5e043a19cade2f4a0)

**Comment by josecelano** [comment]
https://github.com/tcort/markdown-link-check/issues/201
