### ISSUE TITLE
Merging dependabot's PRs directly does not build the app

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/git-queue#136]
I've just realized that PR created by `dependabot` does not contain the built app. We can do it manually before merging with a commit amend or create a new issue to update all dependencies as we did here:

- https://github.com/Nautilus-Cyberneering/git-queue/issues/132
- https://github.com/Nautilus-Cyberneering/git-queue/issues/116

I personally prefer the second option.

Pros:

- Build once
- Update all

Cons:

- You have to review all dependabot's PRs and close them manually and be sure you do not close the github actions updates.

Regarding PR related to GitHub Actions version I workflows I suppose we do not need to build the action if only workflows change.

@da2ce7 @yeraydavidrodriguez

**Comment by da2ce7** [comment]
@josecelano We should enforce a build of the application in every commit (with some sort of workflow), except for commits that only edit the `.github` folder.

**Comment by josecelano** [comment]
> @josecelano We should enforce a build of the application in every commit (with some sort of workflow), except for commits that only edit the `.github` folder.

OK, then I will update the README to explain our policy to use dependabot:

1. For GitHub Actions upgrades we can merge directly using GitHub button.
2. For node modules upgrades we can either reuse the dependabot branch and build the app or create a new issue to update dependencies.

**Comment by da2ce7** [comment]
@josecelano if we are running the `yarn build && yarn package` check for every commit, it doesn't hurt to run it for the `.github` updates; just there should be no changes...

**Comment by josecelano** [comment]
Add also another good practice [proposed](https://github.com/Nautilus-Cyberneering/git-queue/pull/139#issuecomment-1098004017) by @da2ce7

>When we integrate a new dependency, or upgrade dependencies, each indivisible dependency >change (update, remove, add) should have it's own commit should including:
>
>Updated package.json file.
>Updated yarn.lock
>Regenerated dist directory.
>Updated documentation, if needed.
>Minimal changes to the code to accommodate the change in the dependencies.

**Comment by josecelano** [comment]
@da2ce7 my idea is to add a new section inside the "Release" section of the README because I think this is related to the release process and make the action executable for each commit.

Since we have started a discussion about this topic I would also like to review the whole "Release" section in the README. To be honest part of the text was inherited from the [template](https://github.com/actions/typescript-action) we forked. There is something I don't understand:

```bash
yarn package
git add dist
git commit -a -m "prod dependencies"
git push origin releases/v1
```

I do not know why they use a "release" branch. The [official documentation](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md) is also confusing.

At the moment we are only using the "main" branch for releases. In fact, we release automatically with the [publish-github-release.yml](https://github.com/Nautilus-Cyberneering/git-queue/blob/main/.github/workflows/publish-github-release.yml) workflow.

Am I missing something? What do we need that "release" branch for? In the beginning, I thought that was the default branch GitHub used to get the releases from.

**Comment by josecelano** [comment]
> @da2ce7 my idea is to add a new section inside the "Release" section of the README because I think this is related to the release process and make the action executable for each commit.
> 
> Since we have started a discussion about this topic I would also like to review the whole "Release" section in the README. To be honest, part of the text was inherited from the [template](https://github.com/actions/typescript-action) we forked. There is something I don't understand:
> 
> ```shell
> yarn package
> git add dist
> git commit -a -m "prod dependencies"
> git push origin releases/v1
> ```
> 
> I do not know why they use a "release" branch. The [official documentation](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md) is also confusing.
> 
> At the moment we are only using the "main" branch for releases. In fact, we release automatically with the [publish-github-release.yml](https://github.com/Nautilus-Cyberneering/git-queue/blob/main/.github/workflows/publish-github-release.yml) workflow.
> 
> Am I missing something? What do we need that "release" branch for? In the beginning, I thought that was the default branch GitHub used to get the releases from.

It might be related to [release-isolation](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/branching-strategies-with-tfvc?view=azure-devops#release-isolation) or to [Deployment branches](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-branches).
