### ISSUE TITLE
Add `CONTRIBUTING.md`and `CODE_OF_CONDUCT.md` files

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/git-queue#238]
Add a [CONTRIBUTING.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#adding-a-contributing-file) and [CODE_OF_CONDUCT.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project) files.

We can use these ones as templates:

- [CONTRIBUTING.md](https://github.com/Nautilus-Cyberneering/nautilus-librarian/blob/main/CONTRIBUTING.md)
- [CODE_OF_CONDUCT.md](https://github.com/Nautilus-Cyberneering/nautilus-librarian/blob/main/CODE_OF_CONDUCT.md)

**Comment by cgbosse** [comment]
I will create the documentation.
