### ISSUE TITLE
Use a `json` commit body to include queue metadata

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/git-queue#24]
As we were discussing [here](https://github.com/josecelano/library-consumer/issues/4), it would be convenient to allow the queue to add metadata in the commit body. I think this was the final version:

### Commit body

NewJobMessage:

```
{
  "name": "create-job",
  "metadata": {
     "version": 1,
  }
  "payload": "{\"previous_ref\": \"...\",\n     \"current_ref\": \"...\",\n     \"submodule\": \"...\",\n     \"submoudle_url\": \"...\",\n}"
}
```

StartJobMessage:

```
{
  "name": "begin-job",
  "metadata": {
     "version": 1,
     "job_number": 1,
     "job_commit": "0fdf0db843a2010702b7c8d2e446966e9302f40e",
  },
  "payload": ""
}
```

FinishJobMessage:

```
{
  "name": "finish-job",
  "metadata": {
     "version": 1,
     "job_number": 1,
     "job_commit": "0fdf0db843a2010702b7c8d2e446966e9302f40e",
  },
  "payload": ""
}
```

@da2ce7 @yeraydavidrodriguez please review this.

**Comment by da2ce7** [comment]
I would like to use and enforce a JSON SCHEMA: We could use https://github.com/ajv-validator/ajv for example.
