### ISSUE TITLE
Format and validate queue name

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/git-queue#39]
We are adding the queue name to the commit subject:

```text
📝✅: queue_name: job.ref.1e31b549c630f806961a291b4e3d4a1471f37490
```

[Git recommends keeping the commit first line (commit subject) with less than 50 characters](https://git-scm.com/docs/git-commit#_discussion).

I think it's a good idea to limit the queue size to **30 characters**.

We can also replace special characters:

My proposal is to accept only lowercase letters from a to z, dash and white space. But we replace the whitespace by a `-`

Regexp: https://regex101.com/r/Hd2nQA/1

Valid examples:

```text
queue
queue-name
queue name -> queue-name
```

Invalid examples:

```text
📝
long-----------------queue-name (31 chars)
QueueName
!"·$%&/()=?¿[]ḉ{}.:;name
queue name -> queue-name
ABCDEFGHIJKLMNÑOPQRSTUVWXYZ
```

Any other suggestion @da2ce7 @yeraydavidrodriguez ? We could also replace or remove all invalid characters.

**Comment by da2ce7** [comment]
Sounds good.

Reasonable Limitations for the Queue Name.

:)

Cam.


Von meinem iPhone gesendet

**Comment by josecelano** [comment]
Maybe we can also accept underscore: `queue_name`.

**Comment by yeraydavidrodriguez** [comment]
I'm starting implementation on this now.

I would not perform any other character transformation than replacing whitespaces by "-". The reason is that we could have collisions between queues. For instance, if we perform upper to lowercase transformation (or any other kind of character translation or removal), if we already have a queue named "test", and the queue "TEST" is created, both will be mixed.

Instead, I would throw an "Invalid queue name" exception if the validation is not passed.

What do you think, @josecelano @da2ce7 ?

**Comment by josecelano** [comment]
> I'm starting implementation on this now.
> 
> I would not perform any other character transformation than replacing whitespaces by "-". The reason is that we could have collisions between queues. For instance, if we perform upper to lowercase transformation (or any other kind of character translation or removal), if we already have a queue named "test", and the queue "TEST" is created, both will be mixed.
> 
> Instead, I would throw an "Invalid queue name" exception if the validation is not passed.
> 
> What do you think, @josecelano @da2ce7 ?

hi @yeraydavidrodriguez yes, I think we should either only validate the name or fully transform it like URL encode. Something in the middle might be confusing. So I would say to keey only validation and let the user change it.

**Comment by josecelano** [comment]
hi @da2ce7 @yeraydavidrodriguez I've just realized we do not accept numbers in the queue name:

https://github.com/Nautilus-Cyberneering/chinese-ideographs-website/issues/45

It's OK, but it was not the behaviour I was expecting :-), just to make you aware of it.
