### ISSUE TITLE
Add workflow ID to commit message

### ISSUE THREAD

**Issue by yeraydavidrodriguez** [Nautilus-Cyberneering/git-queue#82]
Currently, commit messages includes the queue name and a job reference (hash):

`📝👔: my-queue: job.ref.ddda55e3c04b05a1975034ab468939f75a5861fb`

However, when something unexpected occurs, it could be pretty difficult to debug with that information, as is not easy to know which workflow has created this commit.

A solution for this could be adding the workflow run ID to the commit message. Something like: 

`📝👔: my-queue: job.ref.ddda55e3c04b05a1975034ab468939f75a5861fb wf.run.512`

In the previous example, we could go to the github actions view of the workflow that performs the job and look for the execution with ID 512, and inspect all the messages and logs.

**Comment by da2ce7** [comment]
Should we put the full-link in the comment message?

**Comment by josecelano** [comment]
> Should we put the full-link in the comment message?

Hi @da2ce7 ,I was discussing this with @yeraydavidrodriguez this morning and I thought it was a good idea but I've changed my mind. I don't think we should  couple the action core domain to Github Actions. It could be used in the future with other CI/CD infrastructure. I think the user of the action can have their own metadata in the payload. If we decide to include such information, it should be something more generic like `worker_process_output_url`. In any case, the user should be responsible to provide the url and it's up to them which one to use.

**Comment by josecelano** [comment]
I'm going to close this issue. I assume that is better to put that information in the [custom payload](https://github.com/Nautilus-Cyberneering/chinese-ideographs-website/issues/26) because of the reasons mentioned above.
